# Generated by Django 5.0.4 on 2024-05-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("User", "0006_rename_is_admin_user_isadmin_user_numero"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("messsageId", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=25)),
                ("created_at", models.DateTimeField()),
                ("user", models.ManyToManyField(to="User.user")),
            ],
        ),
    ]
