# Generated by Django 5.0.4 on 2024-05-19 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Message", "0001_initial"),
        ("User", "0006_rename_is_admin_user_isadmin_user_numero"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="User.user"
            ),
        ),
    ]
