# Generated by Django 5.0.4 on 2024-05-19 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Message", "0002_remove_message_user_message_user"),
        ("User", "0006_rename_is_admin_user_isadmin_user_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="user2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_received",
                to="User.user",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_sent",
                to="User.user",
            ),
        ),
    ]
