# Generated by Django 5.0.4 on 2024-05-19 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Message", "0003_message_user2_alter_message_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="user2",
            new_name="receiver",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="user",
            new_name="sender",
        ),
    ]
