# Generated by Django 5.0.4 on 2024-05-19 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Poster", "0005_alter_poster_added_at_alter_poster_imageurl_and_more"),
        ("User", "0005_remove_user_posters"),
    ]

    operations = [
        migrations.CreateModel(
            name="Command",
            fields=[
                ("commandId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "poster",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Poster.poster",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.user",
                    ),
                ),
            ],
        ),
    ]
