# Generated by Django 5.0.4 on 2024-05-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Command", "0001_initial"),
        ("Poster", "0005_alter_poster_added_at_alter_poster_imageurl_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="command",
            name="poster",
        ),
        migrations.AddField(
            model_name="command",
            name="poster",
            field=models.ManyToManyField(to="Poster.poster"),
        ),
    ]
