# Generated by Django 5.0.4 on 2024-05-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Command", "0002_remove_command_poster_command_poster"),
    ]

    operations = [
        migrations.RenameField(
            model_name="command",
            old_name="commandId",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="command",
            old_name="poster",
            new_name="posters",
        ),
        migrations.AddField(
            model_name="command",
            name="location",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
