# Generated by Django 5.0.4 on 2024-05-21 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Command", "0003_rename_commandid_command_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="command",
            old_name="posters",
            new_name="poster",
        ),
    ]
