# Generated by Django 5.0.4 on 2024-05-21 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Command", "0005_rename_poster_command_posters"),
    ]

    operations = [
        migrations.RenameField(
            model_name="command",
            old_name="user",
            new_name="userId",
        ),
    ]
