# Generated by Django 5.0.4 on 2024-05-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poster",
            fields=[
                ("postId", models.AutoField(primary_key=True, serialize=False)),
                ("imageURL", models.URLField()),
                ("dscription", models.CharField(max_length=25)),
            ],
        ),
    ]
