# Generated by Django 5.0.4 on 2024-05-17 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Post", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Poster",
            new_name="Post",
        ),
    ]
