# Generated by Django 5.0.4 on 2024-05-19 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Post", "0002_rename_poster_post"),
        ("User", "0003_rename_user_id_user_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="User.user"
            ),
        ),
    ]
