# Generated by Django 5.0.4 on 2024-05-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Post", "0004_rename_dscription_post_description_alter_post_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="imageURL",
            field=models.ImageField(upload_to=""),
        ),
    ]
