# Generated by Django 5.0.4 on 2024-05-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Post", "0005_alter_post_imageurl"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user",
            new_name="userId",
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.IntegerField(null=True),
        ),
    ]
