# Generated by Django 5.0.4 on 2024-05-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Post", "0007_alter_post_imageurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="imageURL",
            field=models.CharField(max_length=25),
        ),
    ]
