# Generated by Django 5.0.4 on 2024-05-21 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Post", "0008_alter_post_imageurl"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="postId",
            new_name="id",
        ),
    ]
