# Generated by Django 5.0.4 on 2024-05-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=25)),
                ("password", models.CharField(max_length=25)),
                ("email", models.CharField(max_length=25)),
                ("is_admin", models.BooleanField()),
            ],
        ),
    ]
