# Generated by Django 5.0.4 on 2024-05-05 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0002_rename_users_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_id",
            new_name="userId",
        ),
    ]
