# Generated by Django 5.0.4 on 2024-05-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Poster", "0004_alter_poster_imageurl"),
        ("User", "0003_rename_user_id_user_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="posters",
            field=models.ManyToManyField(to="Poster.poster"),
        ),
    ]
