# Generated by Django 5.0.4 on 2024-05-19 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0004_user_posters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="posters",
        ),
    ]
