# Generated by Django 5.0.4 on 2024-05-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0005_remove_user_posters"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_admin",
            new_name="isAdmin",
        ),
        migrations.AddField(
            model_name="user",
            name="numero",
            field=models.IntegerField(null=True),
        ),
    ]
