# Generated by Django 5.0.4 on 2024-05-21 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Post", "0008_alter_post_imageurl"),
        ("User", "0006_rename_is_admin_user_isadmin_user_numero"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=25)),
                (
                    "postId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Post.post",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.user",
                    ),
                ),
            ],
        ),
    ]
