# Generated by Django 5.0.4 on 2024-05-05 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Poster", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poster",
            old_name="PosterId",
            new_name="posterId",
        ),
    ]
