# Generated by Django 5.0.4 on 2024-05-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Poster", "0002_rename_posterid_poster_posterid"),
    ]

    operations = [
        migrations.AddField(
            model_name="poster",
            name="imageURL",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
