# Generated by Django 5.0.4 on 2024-05-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Poster", "0003_poster_imageurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="imageURL",
            field=models.URLField(),
        ),
    ]
