# Generated by Django 5.0.4 on 2024-05-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Poster", "0004_alter_poster_imageurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="added_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="poster",
            name="imageURL",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="poster",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
