# Generated by Django 5.0.4 on 2024-05-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Poster", "0005_alter_poster_added_at_alter_poster_imageurl_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="imageURL",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
