# Generated by Django 5.0.4 on 2024-05-21 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Poster", "0006_alter_poster_imageurl"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poster",
            old_name="imageURL",
            new_name="posterFile",
        ),
    ]
